const fs = require('fs');
const PDFDocument = require('pdfkit');
const { drawResumeCard } = require('../utils/pdfHelpers');

const outputPath = '/tmp/sample_applications.pdf';
const doc = new PDFDocument({ margin: 50, size: 'A4' });
const stream = fs.createWriteStream(outputPath);
doc.pipe(stream);

// Header
doc.fontSize(24).fillColor('#1e40af').text('NavGurukul', 50, 50);
doc.fontSize(10).fillColor('#64748b').text('Placement Dashboard', 50, 78);

// Title
doc.fontSize(18).fillColor('#000').text('Job Applications Report - Sample', 50, 110, { align: 'center' });

let y = 160;

const sampleApps = [
  {
    student: {
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      phone: '+91-9876543210',
      avatar: '',
      campus: { name: 'Jashpur' },
      studentProfile: {
        about: 'Motivated web developer/designer with experience in JS/React.',
        technicalSkills: [{ skillName: 'JavaScript' }, { skillName: 'React' }, { skillName: 'HTML' }, { skillName: 'CSS' }],
        higherEducation: [{ degree: 'BSc Computer Science', endYear: 2020 }],
        linkedIn: 'https://linkedin.com/in/johndoe',
        github: 'https://github.com/johndoe',
        hometown: { district: 'Jashpur', state: 'Chhattisgarh' }
      }
    },
    status: 'Applied',
    createdAt: new Date()
  },
  {
    student: {
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane.smith@example.com',
      phone: '+91-9123456780',
      avatar: '',
      campus: { name: 'Dharamshala' },
      studentProfile: {
        about: 'Recent bootcamp grad specialized in full-stack development.',
        technicalSkills: [{ skillName: 'Node.js' }, { skillName: 'Express' }, { skillName: 'MongoDB' }],
        higherEducation: [{ degree: 'BA Economics', endYear: 2019 }],
        linkedIn: 'https://linkedin.com/in/janesmith',
        github: 'https://github.com/janesmith',
        hometown: { district: 'Dharamshala', state: 'HP' }
      }
    },
    status: 'Interviewed',
    createdAt: new Date()
  }
];

const cardsPerPage = 2;
const pagePaddingTop = y;
const availableHeight = doc.page.height - pagePaddingTop - 120;
const cardHeight = Math.floor((availableHeight - 10) / cardsPerPage);
const cardWidth = 495;

sampleApps.forEach((app, index) => {
  const isFirstOnPage = (index % cardsPerPage) === 0;
  if (isFirstOnPage && index !== 0) {
    doc.addPage();
  }
  const startY = isFirstOnPage ? pagePaddingTop : pagePaddingTop + cardHeight + 10;
  drawResumeCard(doc, app, 50, startY, cardWidth, cardHeight);
});

// Footer
const footerY = doc.page.height - 60;
doc.fontSize(8).fillColor('#9ca3af').text('Generated by NavGurukul Placement Dashboard', 50, footerY).text(new Date().toISOString().split('T')[0], 450, footerY);

doc.end();

stream.on('finish', () => {
  console.log('Sample PDF generated at', outputPath);
});
