const fs = require('fs');
const PDFDocument = require('pdfkit');
const { drawResumeCard } = require('../utils/pdfHelpers');

function createSample(count, outPath) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  const stream = fs.createWriteStream(outPath);
  doc.pipe(stream);

  doc.fontSize(24).fillColor('#1e40af').text('NavGurukul', 50, 50);
  doc.fontSize(10).fillColor('#64748b').text('Placement Dashboard', 50, 78);
  doc.fontSize(18).fillColor('#000').text('Job Applications Report - Sample', 50, 110, { align: 'center' });

  let y = 160;
  const sampleApps = [];
  for (let i = 0; i < count; i++) {
    sampleApps.push({
      student: {
        firstName: `Student${i + 1}`,
        lastName: 'Test',
        email: `student${i + 1}@example.com`,
        phone: `+91-90000000${i}`,
        avatar: '',
        campus: { name: 'Test Campus' },
        studentProfile: {
          about: 'This is a short summary about the student. Strong in problem solving and communication. Has worked on projects involving web development and data processing.',
          technicalSkills: [{ skillName: 'JS' }, { skillName: 'React' }, { skillName: 'Node' }],
          higherEducation: [{ degree: 'BSc', endYear: 2020 }],
          linkedIn: '', github: '', portfolio: '',
          hometown: { district: 'Mumbai', state: 'MH' }
        }
      },
      status: i % 3 === 0 ? 'Selected' : i % 3 === 1 ? 'Interviewed' : 'Applied',
      createdAt: new Date()
    });
  }

  const cardsPerPage = 2;
  const pagePaddingTop = y;
  const availableHeight = doc.page.height - pagePaddingTop - 120;
  const cardHeight = Math.floor((availableHeight - 10) / cardsPerPage);
  const cardWidth = 495;

  sampleApps.forEach((app, index) => {
    const isFirstOnPage = (index % cardsPerPage) === 0;
    if (isFirstOnPage && index !== 0) {
      doc.addPage();
    }
    const startY = isFirstOnPage ? pagePaddingTop : pagePaddingTop + cardHeight + 10;
    drawResumeCard(doc, app, 50, startY, cardWidth, cardHeight);
  });

  // Footer
  const footerY = doc.page.height - 60;
  doc.fontSize(8).fillColor('#9ca3af').text('Generated by NavGurukul Placement Dashboard', 50, footerY).text(new Date().toISOString().split('T')[0], 450, footerY);
  doc.end();

  stream.on('finish', () => console.log('Generated:', outPath));
}

createSample(7, '/tmp/sample_7_resume.pdf');
createSample(2, '/tmp/sample_2_resume.pdf');
